CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "./demo_logs"

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<|image|>"

ALL_IMG_TOKENS = [f"[IMG{i}]" for i in range(0,10)]
ALL_IMG_TOKENS_STR = " ".join(ALL_IMG_TOKENS)
